server:
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        jdbc:
          batch_size: 100

logging:
  level:
    org.hibernate.SQL: DEBUG
    my.bbs: DEBUG